#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display info about subdomains.

# Function to retrieve and display info about a subdomain
domain_info () {
	# Perform DNS lookup for the subdomain under the specified domain
	line=$(dig "$2" "$1" \ grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	# Extract and print relevant info
	echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and point to " $3}'
}

# Check the number of arguments passed to the script 
if [ "$#" == 1 ]
then 
	# if there is only one argument,
	# call the domain_information function with predefined subdomain names
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	# If there are two arguments, call the domain_info \ function with the subdomain name
	domain_info "$1" "$2"
fi
