#!/usr/bin/env bash
# remove the deafult config file
rm /etc/nginx/sites-enabled/default
# Config nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
